spring.application.name=demologinregisrationbackend

spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=springpract
spring.datasource.password=springpract

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey12345
server.port=8090